sort out networking entries

diff --git a/client-pwa/Dockerfile b/client-pwa/Dockerfile
--- a/client-pwa/Dockerfile
+++ b/client-pwa/Dockerfile
@@ -1,6 +1,6 @@
-FROM node:lts-alpine as build-stage
+FROM node:lts as build-stage
 
-LABEL name="real-westher web"
+LABEL name="real-weather web"
 ENV APP_PORT=4000 APP_DIR=/app
 
 WORKDIR $APP_DIR
@@ -11,20 +11,22 @@ RUN cat tsconfig-build.json
 RUN yarn install --frozen-lock-file 
 RUN yarn build
 
-# FROM node:alpine:18.15.1 as deploy-stage
-# ADD dist .
-# ADD public .
-FROM node:lts-alpine as deploy-stage
-# WORKDIR /var/www/html
-WORKDIR /app
-# COPY --from=build-stage /app/dist /usr/local/apache2/htdocs/
-COPY --from=build-stage /app/dist .
-COPY package.json .
-RUN yarn install --frozen-lock-file 
+# FROM node:lts-alpine as deploy-stage
+# WORKDIR /app
+# COPY --from=build-stage /app/dist .
 
-HEALTHCHECK --interval=15s --timeout=10s --retries=3 CMD curl -f http://localhost:$APP_PORT || exit 1
+# HEALTHCHECK --interval=15s --timeout=10s --retries=3 CMD curl -f http://localhost:$APP_PORT || exit 1
 
-EXPOSE $APP_PORT
+# EXPOSE $APP_PORT
 
-ENTRYPOINT [ "yarn", "start" ]
+# ENTRYPOINT [ "yarn", "start" ]
 
+FROM nginx
+
+WORKDIR /usr/share/nginx/html
+
+RUN rm /etc/nginx/conf.d/default.conf
+COPY --from=build-stage  /app/dist .
+COPY deployment/*.conf /etc/nginx/conf.d
+
+ENTRYPOINT ["nginx", "-g", "daemon off;"]
